Repository sunriseos/SunriseOS, pull requests merged in 2019-08, with the labels that each got.

#360 Clean up usage of byteorder
  Cargo.lock
  kernel/Cargo.toml
  kernel/src/ipc/session.rs
  kernel/src/process/capabilities.rs
  libuser/src/ipc/mod.rs
  shell/Cargo.toml
  shell/src/main.rs
Labels: refactoring

#410 Add get-frame-sizes command
  scripts/gdb/gdbinit
  scripts/gdb/get_frame_sizes.py
Labels: infra

#339 Thread local storage
  Cargo.lock
  ahci/src/main.rs
  i386-unknown-none-user.json
  i386-unknown-none.json
  kernel/Cargo.toml
  kernel/res/bsod.bmp
  kernel/res/cpu_locals_segmentation_doc.gif
  kernel/res/double_fault.txt
  kernel/res/kernel_fault.txt
  kernel/res/kernel_panic_doc.jpg
  kernel/src/cpu_locals.rs
  kernel/src/i386/gdt.rs
  kernel/src/i386/mod.rs
  kernel/src/i386/process_switch.rs
  kernel/src/i386/structures/idt.rs
  kernel/src/interrupts/irq.rs
  kernel/src/interrupts/mod.rs
  kernel/src/interrupts/syscalls.rs
  kernel/src/main.rs
  kernel/src/paging/arch/i386/table.rs
  kernel/src/paging/arch/mod.rs
  kernel/src/paging/mod.rs
  kernel/src/panic.rs
  kernel/src/process.rs
  kernel/src/process/thread_local_storage.rs
  kernel/src/scheduler.rs
  libkern/Cargo.toml
  libkern/src/lib.rs
  libuser/src/crt0/mod.rs
  libuser/src/crt0/relocation.rs
  libuser/src/lib.rs
  libuser/src/syscalls.rs
  libuser/src/thread_local_storage.rs
  libuser/src/threads.rs
  libuser/src/types.rs
  linker-scripts/kernel.ld
  linker-scripts/userspace.ld
  shell/src/main.rs
  sm/src/main.rs
  time/src/main.rs
  vi/src/main.rs
  wall-clock/src/main.rs
Labels: feature, project-kernel, project-libuser

#416 Kernel: Fix TLS doc meme links
  kernel/src/cpu_locals.rs
  kernel/src/panic.rs
Labels: good first issue, project-kernel

#417 Refacto interrupt folder
  kernel/res/syscalls_doc.jpg
  kernel/src/cpu_locals.rs
  kernel/src/i386/gdt.rs
  kernel/src/i386/interrupt_service_routines.rs
  kernel/src/i386/mod.rs
  kernel/src/main.rs
  kernel/src/paging/process_memory.rs
  kernel/src/panic.rs
  kernel/src/process.rs
  kernel/src/syscalls.rs
Labels: project-kernel, refactoring

#431 Libuser: fix TLS linker symbols
  libuser/src/thread_local_storage.rs
  linker-scripts/userspace.ld
Labels: bug, project-kernel

#432 Make doctests work on libraries, fix docs
  Makefile.toml
  libuser/src/caps.rs
  libuser/src/error.rs
  libuser/src/ipc/mod.rs
  libuser/src/ipc/server.rs
  libuser/src/mem.rs
  libuser/src/syscalls.rs
  libuser/src/thread_local_storage.rs
  libutils/src/io/mmio.rs
  libutils/src/lib.rs
  swipc-gen/src/gen_rust_code.rs
  swipc-parser/src/lib.rs
Labels: infra

#434 Update to mergeable v2
  .github/mergeable.yml
Labels: infra

#433 Update to cargo-make 0.22.0
  .travis.yml
  Makefile.toml
  docs/BUILDING.md
Labels: infra

#445 Use debug! when appropriate
  kernel/src/event.rs
  kernel/src/ipc/port.rs
  kernel/src/ipc/session.rs
Labels: project-kernel

#447 SM: Fix hang when multiple futures wait on EVENT
  libuser/src/types.rs
  sm/src/main.rs
  time/src/main.rs
Labels: bug, project-sm

#452 Fix read_from_temp_storage assert
  fs/src/interface/storage.rs
Labels: bug

#454 Switch to bitfield official releases
  Cargo.lock
  ahci/Cargo.toml
  kernel/Cargo.toml
Labels: project-kernel

#453 Remove load_video in grub.cfg
  isofiles/boot/grub/grub.cfg
Labels: bug

#459 Kernel: unconditionally switch gs entering kernel
  kernel/src/i386/interrupt_service_routines.rs
Labels: bug, project-kernel
